/**
 * SmartSuggestionsBar — Proactive actionable insight chips for XS Agent
 *
 * Displays real-time business insights as clickable action chips
 * above the chat input area. Insights are generated by SmartInsightsEngine.
 */

import React, { useState, useEffect, useCallback } from 'react';
import { Sparkles, AlertTriangle, Clock, Info, CheckCircle2, ChevronRight, RefreshCw, X } from 'lucide-react';
import { smartInsightsEngine, Insight, InsightSeverity } from '../services/smartInsightsEngine';

interface SmartSuggestionsBarProps {
  companyId: string;
  onActionCommand?: (command: string) => void;
  className?: string;
}

const SEVERITY_CHIP: Record<InsightSeverity, { bg: string; border: string; dot: string; text: string }> = {
  critical: { bg: 'bg-red-50 hover:bg-red-100', border: 'border-red-200', dot: 'bg-red-500', text: 'text-red-700' },
  warning: { bg: 'bg-amber-50 hover:bg-amber-100', border: 'border-amber-200', dot: 'bg-amber-500', text: 'text-amber-700' },
  info: { bg: 'bg-blue-50 hover:bg-blue-100', border: 'border-blue-200', dot: 'bg-blue-500', text: 'text-blue-700' },
  success: { bg: 'bg-emerald-50 hover:bg-emerald-100', border: 'border-emerald-200', dot: 'bg-emerald-500', text: 'text-emerald-700' },
};

const SmartSuggestionsBar: React.FC<SmartSuggestionsBarProps> = ({ companyId, onActionCommand, className = '' }) => {
  const [suggestions, setSuggestions] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);
  const [dismissed, setDismissed] = useState<Set<string>>(new Set());
  const [refreshing, setRefreshing] = useState(false);

  const loadSuggestions = useCallback(async () => {
    try {
      const data = await smartInsightsEngine.getSmartSuggestions(companyId, 6);
      setSuggestions(data);
    } catch (err) {
      console.warn('[SmartSuggestions] Error:', err);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [companyId]);

  useEffect(() => {
    loadSuggestions();
    // Refresh every 5 minutes
    const interval = setInterval(loadSuggestions, 5 * 60 * 1000);
    return () => clearInterval(interval);
  }, [loadSuggestions]);

  const handleRefresh = () => {
    setRefreshing(true);
    smartInsightsEngine.clearCache();
    loadSuggestions();
  };

  const handleDismiss = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setDismissed(prev => new Set(prev).add(id));
  };

  const visibleSuggestions = suggestions.filter(s => !dismissed.has(s.id));

  if (loading || visibleSuggestions.length === 0) return null;

  return (
    <div className={`${className}`}>
      <div className="flex items-center gap-2 mb-1.5">
        <Sparkles size={12} className="text-indigo-500" />
        <span className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider">Smart Insights</span>
        <button
          onClick={handleRefresh}
          className="ml-auto p-1 hover:bg-slate-100 rounded text-slate-400 hover:text-slate-600 transition-colors"
          title="Refresh insights"
        >
          <RefreshCw size={11} className={refreshing ? 'animate-spin' : ''} />
        </button>
      </div>

      <div className="flex flex-wrap gap-1.5">
        {visibleSuggestions.slice(0, 4).map(insight => {
          const style = SEVERITY_CHIP[insight.severity];
          return (
            <button
              key={insight.id}
              onClick={() => onActionCommand?.(insight.actionCommand || '')}
              className={`group flex items-center gap-1.5 ${style.bg} ${style.border} border rounded-full px-3 py-1.5 transition-all text-xs hover:shadow-sm`}
            >
              <span className={`w-1.5 h-1.5 rounded-full ${style.dot} shrink-0`} />
              <span className={`${style.text} font-medium truncate max-w-[180px]`}>{insight.title}</span>
              <ChevronRight size={12} className={`${style.text} opacity-0 group-hover:opacity-100 transition-opacity shrink-0`} />
              <span
                onClick={(e) => handleDismiss(insight.id, e)}
                className="opacity-0 group-hover:opacity-100 transition-opacity ml-0.5 text-slate-400 hover:text-slate-600"
              >
                <X size={10} />
              </span>
            </button>
          );
        })}
      </div>
    </div>
  );
};

export default SmartSuggestionsBar;
